# Generated by Django 5.1.4 on 2024-12-28 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'User Progress', 'verbose_name_plural': 'User Progress'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='word',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='unique_user_word'),
        ),
    ]
